[package]
name = "futures-async-stream"
version = "0.1.0-alpha.7"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream/"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous"]
readme = "README.md"
description = """
Async stream for Rust and the futures crate.
"""

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["futures-async-stream-macro"]

[features]

[dependencies]
futures-async-stream-macro = { version = "=0.1.0-alpha.7", path = "futures-async-stream-macro", default-features = false }
futures-core-preview = { version = "0.3.0-alpha.19", default-features = false }
pin-project = "0.4"

[dev-dependencies]
trybuild = "1.0"
futures-util-preview = "0.3.0-alpha.19"
tokio = "0.2.0-alpha.6"
