[package]
name = "futures-async-stream"
version = "0.1.0-alpha.6"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream/"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous"]
readme = "README.md"
description = """
Async stream for Rust and the futures crate.
"""

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["futures-async-stream-macro"]

[features]

[dependencies]
futures-async-stream-macro = { version = "=0.1.0-alpha.6", path = "futures-async-stream-macro", default-features = false }
futures-core-preview = { version = "0.3.0-alpha.18", default-features = false }
pin-project = "=0.4.0-beta.1"

[dev-dependencies]
compiletest = { version = "0.3.21", package = "compiletest_rs", features = ["stable", "tmp"] }
futures-preview = "0.3.0-alpha.18"
romio = "0.3.0-alpha.10"
