[package]
name = "futures-async-stream"
version = "0.1.0-alpha.3"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream/"
readme = "README.md"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous"]
description = """
Async stream for Rust and the futures crate.
"""

[workspace]
members = ["futures-async-stream-macro"]

[features]

[dependencies]
futures-async-stream-macro = { version = "=0.1.0-alpha.3", path = "futures-async-stream-macro", default-features = false }
futures-core-preview = { version = "0.3.0-alpha.18", default-features = false }
pin-project = { version = "0.4.0-alpha.3", default-features = false }

[dev-dependencies]
compiletest = { version = "0.3.21", package = "compiletest_rs", features = ["stable", "tmp"] }
futures-preview = "0.3.0-alpha.18"
romio = "0.3.0-alpha.9"
