[package]
name = "futures-async-stream-macro"
version = "0.1.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/futures-async-stream"
homepage = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream-macro/"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous"]
description = """
Definition of the `#[async_stream]` macro for the `futures-async-stream` crate as well as a few other assorted macros.
"""

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut"] }
