[package]
name = "futures-async-stream-macro"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.1.0-alpha.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = """
Definition of the `#[async_stream]` macro for the `futures-async-stream` crate as well as a few other assorted macros.
"""
repository = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream-macro/"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous"]

[lib]
proc-macro = true

[features]

[dependencies]
proc-macro2 = "0.4.13"
quote = "0.6.8"
syn = { version = "0.15.41", features = ["full", "visit-mut"] }
